//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Requerimientos_ST.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requerimientos
    {
        public int Id { get; set; }
        public Nullable<int> Area { get; set; }
        public Nullable<int> Aplicativo { get; set; }
        public string Alcance { get; set; }
        public Nullable<System.DateTime> FechaSolicitud { get; set; }
        public Nullable<int> Prioridad { get; set; }
        public Nullable<int> Desarrollador { get; set; }
        public Nullable<System.DateTime> FechaDesarrollo { get; set; }
        public Nullable<System.DateTime> FechaPrueba { get; set; }
        public string MotivoDeCambio { get; set; }
        public string Justificacion { get; set; }
    
        public virtual Aplicativos Aplicativos { get; set; }
        public virtual Areas Areas { get; set; }
        public virtual Desarrolladores Desarrolladores { get; set; }
        public virtual Prioridades Prioridades { get; set; }
    }
}
